permalink: pretty
excerpt_separator: <!--more-->
skin: gruvbox-material-light

include:
  - _pages

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - 
    scope:
      path: "_pages"
    values:
      permalink: "/:basename:output_ext"

  -
    scope:
      path: ""
      type: "posts" 
    values:
      layout: "post"

  - 
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

collections:
  projects:
    output: true
    order:
      - pocket_chef.md

social_links:
 - { platform: github, user_url: "https://github.com/wigsinator" }