permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts" 
    values:
      layout: "post"

collections:
  projects:
    order:
      - pocket_chef.md