permalink: pretty
excerpt_separator: <!--more-->

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts" 
    values:
      layout: "post"
  - 
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

collections:
  projects:
    output: true
    order:
      - pocket_chef.md