permalink: pretty
excerpt_separator: <!--more-->
skin: gruvbox-material-light
timezone: Canada/Eastern

include:
  - _pages

plugins:
  - jekyll-feed

# For Jekyll Feed Purposes
title: William Hirsch's blog
description: Assorted longform thoughts to get me back in the habit of enjoying things and thinking critically. 
url: williamhirsch.ca
author: William Hirsch

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - 
    scope:
      path: "_pages"
    values:
      permalink: "/:basename:output_ext"

  -
    scope:
      path: ""
      type: "posts" 
    values:
      layout: "post"

  - 
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

collections:
  projects:
    output: true
    order:
      - pocket_chef.md

social_links:
 - { platform: email,   user_url: "mailto:williamhirsch@williamhirsch.ca"}
 - { platform: github,  user_url: "https://github.com/wigsinator" }
 - { platform: rss,     user_url: "/feed.xml" }